### ISSUE TITLE
Error with the input argument

### ISSUE THREAD

**Issue by shkaff** [JP-Ellis/mathematica-notebook-filter#1]
Hello, 

I tried running the filter, but every time I get an error

`$ mathematica-notebook-filter -i input_test.nb -o test.nb
error: The argument '--input <FILE>' requires 1 values, but 2 were provided`

Same goes with --input instead of -i. Sometimes without any change on my side it gives the same error for the --output argument.

The system is MacOSX HighSierra, the installation went without problem, but it never worked.

Thanks!

**Comment by JP-Ellis** [comment]
Did you, by any chance, clone the repository first and then run `cargo update` before installing it?  If so, then this is a known known bug (kbknapp/clap-rs#1050) in the `clap` dependency of `mathematica-notebook-filter`.

I would recommend you install `mathematica-notebook-filter` through 

```
cargo install mathematica-notebook-filter
```

instead of cloning the repository.  If you wish to make changes to the code, then you'll have to revert the update to clap `2.26.0`.

**Comment by shkaff** [comment]
I have installed it through `cargo install mathematica-notebook-filter` and didn't do any other updates on cargo. Is it possible that installing cargo itself dragged that latest version of clap together with this bug?
I'm sorry, I'm really not familiar with Rust (and cargo), how would I check the version of clap installed currently?

**Comment by JP-Ellis** [comment]
For binaries published on crates.io, I believe that all dependencies are always exact, so it must've accidentally been published with version `1.2.0`.

I have released version `1.3.0` which requires `clap = 2.26.0` exactly.  It is available on crates.io and you can update to it with:

```
cargo install --force mathematica-notebook-filter
```

**Comment by shkaff** [comment]
Perfect, that works! Thank you very much for you help and a really great tool!

**Comment by JP-Ellis** [comment]
Good to hear!  Glad you're founding it useful (and let me know if you find any bugs)
