### ISSUE TITLE
working as standalone but not in git workflow

### ISSUE THREAD

**Issue by romanWSgit** [JP-Ellis/mathematica-notebook-filter#2]
When executing it manually your "mathematica-notebook-filter" works like a charm, but not in the git workflow. Any Ideas what i am doing wrong?

**Comment by JP-Ellis** [comment]
Could you double check that you have correctly done all the steps mentioned in [the readme](https://github.com/JP-Ellis/mathematica-notebook-filter#git)?  If that's still causing you issues, feel free to post your `.gitattributes` and `.gitconfig` files.

**Comment by romanWSgit** [comment]
Thanks very much for your fast and kind reply. Its now working in the command line without any problems. The issues seem to correspond to the Tower.app i am using for git on the mac. But i havent found out yet why. i also had to place the .gitattributes file directly in the root of the repository. There may be a path that is not set correctly.  But this way it works. .gitattributes and .gitconfig are the same as you suggested.I appreciate this tool. So thank you very much for that. :-)  If you are interested and i find out more about this issue i'll let you know. I am not so such an expierenced git user so... maybe this is the problem. Greetings for Austria.

**Comment by xwang862** [comment]
I got similar problems that `mathematica-notebook-filter` does not work with the SourceTree app or with the `git` command from Terminal, but it does work manually. Moving `.gitattributes ` to a repository's root folder can fix the problem (thanks to @romanWSgit) but only that specific repository can benefit. Another way is to add the following lines
```
[core]
    attributesfile = ~/.gitattributes
```
to your `~/.gitconfig` so that `git` knows where to consult globally.
