### ISSUE TITLE
Filter not working in SmartGit

### ISSUE THREAD

**Issue by JunkaiDong** [JP-Ellis/mathematica-notebook-filter#7]
Hi. This plugin has been very helpful one week ago, but my computer crashed so I had to reinstall my system. I reinstalled everything, but this filter does not seem to work with SmartGit anymore.

The problem I encountered first was a permission denied warning for `.gitattributes` file. This is successfully solved by moving the file to the root of my repo.

However, as the program runs flawlessly as standalone, I get this warning:

> cannot spawn mathematica-notebook-filter: No such file or directory
cannot fork to run external filter 'mathematica-notebook-filter'
external filter 'mathematica-notebook-filter' failed

My `.gitattributes` file at the root of my repo is as follows: 

`*.nb    filter=dropoutput_nb`

My `.gitconfig` file at `C:\Users\MyName` (since I'm using Windows) is as follows:

```
[user]
	name = My name
	email = My email

[filter "dropoutput_nb"]
    clean = mathematica-notebook-filter
    smudge = cat
```

**Comment by JP-Ellis** [comment]
I'm not familiar with SmartGit and specifics to that I can't really help with.  So with regards to your permission denied error, that's independent to `mathematica-notebook-filter` and you'll need to find a solution elsewhere.

As for your error

> cannot spawn mathematica-notebook-filter: No such file or directory
> cannot fork to run external filter 'mathematica-notebook-filter'
> external filter 'mathematica-notebook-filter' failed

This is because git (or SmartGit) does not know where to find the `mathematica-notebook-filter` binary.  There are two ways to fix this:

1. You can update your [Path variable](`https://en.wikipedia.org/wiki/PATH_(variable)`).  After a cursory Google search, [this SuperUser question](https://superuser.com/q/284342/657861) might be helpful.
2. Instead of just specifying `mathematica-notebook-filter` in your `.gitattributes` file, specify the full path so that it need rely on the Path variable to locate it.

**Comment by JunkaiDong** [comment]
Turns out that I already had the folder containing the program in my PATH variable. The second way works. Thank you very much.

**Comment by JP-Ellis** [comment]
Strange that the folder was already in your PATH variable (though did you reboot your computer?  This might be required before it takes effect).  Glad the second option worked.
